# Generated by Django 5.2.8 on 2025-11-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notificationpreferences_pushtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreferences',
            old_name='email_enabled',
            new_name='email_notifications',
        ),
        migrations.RenameField(
            model_name='notificationpreferences',
            old_name='push_enabled',
            new_name='push_notifications',
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
