# Generated by Django 5.2.8 on 2025-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_enabled_notificationpreferences_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
